safe:         false
exclude:      ['Rakefile','TODO','README.md', 'Gemfile',' Gemfile.lock']
encoding:     "utf-8"

highlighter: rouge
lsi:         false

markdown: kramdown

theme: jekyll-theme-hacker

title: Michael Deimel
description: No comment
show_downloads: false
